// Next 16 dropped `next lint`, and with it the implicit configuration it used
// to supply. The same rule set is now assembled here and run through the eslint
// CLI directly, which is what `npm run lint` does.
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

export default [
  {
    // Generated by the build, not written by anyone: the service worker and its
    // Workbox runtime are minified bundles, and linting them says nothing about
    // this codebase.
    ignores: [
      ".next/**",
      "out/**",
      "node_modules/**",
      "public/sw.js",
      "public/sw.js.map",
      "public/workbox-*.js",
      "public/workbox-*.js.map",
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
];
