import type { AiAnalysis, Book, Flashcard, UserProfile } from "@/lib/types";

export const mockProfile: UserProfile = {
  nativeLanguage: "ru",
  targetLanguage: "de",
  uiLanguage: "ru",
  readingMinutes: 380,
  booksStarted: 3,
  booksFinished: 1,
  savedItems: 128,
};

export const mockBooks: Book[] = [
  {
    id: "monte-cristo-de",
    title: "Граф Монте-Кристо",
    author: "Александр Дюма",
    language: "de",
    format: "epub",
    progress: 42,
    paragraphIndex: 0,
    chapterTitle: "Глава 3. Заговор",
    lastReadAt: "Сегодня",
    coverColor: "linear-gradient(160deg, #c49a28 0%, #7a5c10 100%)",
    paragraphs: [
      "Edmond bemerkte, dass Caderousse leise sprach, während Danglars den Blick nicht von ihm abwandte.",
      "In diesem Augenblick schmiedeten die Männer einen Plan, der das Schicksal des jungen Seemanns verändern sollte.",
      "Mercedes wartete am Fenster, ohne zu ahnen, dass eine verborgene Intrige bereits ihren Lauf nahm.",
    ],
  },
  {
    id: "kleine-prinz",
    title: "Der kleine Prinz",
    author: "Antoine de Saint-Exupéry",
    language: "de",
    format: "epub",
    progress: 12,
    paragraphIndex: 0,
    chapterTitle: "Kapitel 2",
    lastReadAt: "Вчера",
    coverColor: "linear-gradient(160deg, #4a7a5c 0%, #254030 100%)",
    paragraphs: [
      "Der kleine Prinz betrachtete die Sterne und stellte eine Frage, die niemand erwartet hatte.",
    ],
  },
  {
    id: "faust",
    title: "Faust",
    author: "Johann Wolfgang von Goethe",
    language: "de",
    format: "txt",
    progress: 0,
    paragraphIndex: 0,
    chapterTitle: "Начало",
    lastReadAt: "Не начато",
    coverColor: "linear-gradient(160deg, #8a5a2a 0%, #4a2a0a 100%)",
    paragraphs: ["Habe nun, ach! Philosophie, Juristerei und Medizin studiert."],
  },
];

export const mockAnalysis: AiAnalysis = {
  word: {
    text: "schmiedeten",
    lemma: "schmieden",
    partOfSpeech: "глагол",
    translation: "ковали; замышляли",
    explanation: "Здесь слово используется переносно: не буквально ковать металл, а тайно составлять план.",
  },
  phrase: {
    text: "einen Plan schmiedeten",
    translation: "замышляли план",
    type: "устойчивое выражение",
    explanation: "Устойчивая образная фраза. В русском ближе всего: 'строили план' или 'замышляли'.",
  },
  sentence: {
    text: "In diesem Augenblick schmiedeten die Männer einen Plan, der das Schicksal des jungen Seemanns verändern sollte.",
    translation: "В этот момент мужчины замышляли план, который должен был изменить судьбу молодого моряка.",
    grammarNote: "Относительное придаточное с der относится к слову Plan. Sollte добавляет оттенок будущей неизбежности.",
    structure: "Hauptsatz + Relativsatz mit Modalverb",
  },
  examples: [
    { text: "Sie schmiedeten heimlich einen Plan.", translation: "Они тайно замышляли план." },
    { text: "Der König schmiedete ein Bündnis.", translation: "Король заключил союз." },
    { text: "Man kann Eisen schmieden.", translation: "Можно ковать железо." },
    { text: "Die Freunde schmiedeten Reisepläne.", translation: "Друзья строили планы на путешествие." },
    { text: "Danglars schmiedete eine Intrige.", translation: "Данглар замышлял интригу." },
  ],
};

export const mockCards: Flashcard[] = [
  {
    id: "card-1",
    type: "word",
    front: "schmieden",
    back: "ковать; замышлять",
    source: "Граф Монте-Кристо",
    addedAt: new Date().toISOString(),
    status: "review",
    repetitions: 2,
    lapses: 0,
    intervalDays: 4,
    easeFactor: 2.5,
    dueAt: new Date().toISOString(),
    sourceBookId: "monte-cristo-de",
    sourceBookTitle: "Граф Монте-Кристо",
  },
  {
    id: "card-2",
    type: "phrase",
    front: "einen Plan schmieden",
    back: "замышлять / строить план",
    source: "Граф Монте-Кристо",
    addedAt: new Date().toISOString(),
    status: "learning",
    repetitions: 1,
    lapses: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    dueAt: new Date().toISOString(),
    sourceBookId: "monte-cristo-de",
    sourceBookTitle: "Граф Монте-Кристо",
  },
  {
    id: "card-3",
    type: "sentence",
    front: "der das Schicksal verändern sollte",
    back: "который должен был изменить судьбу",
    source: "Граф Монте-Кристо",
    addedAt: new Date().toISOString(),
    status: "new",
    repetitions: 0,
    lapses: 0,
    intervalDays: 0,
    easeFactor: 2.5,
    dueAt: new Date().toISOString(),
    sourceBookId: "monte-cristo-de",
    sourceBookTitle: "Граф Монте-Кристо",
  },
];
